## HW 10: FITS Files and ASTROPY

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [2]:
df = pd.read_csv("solar_system.csv")
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [3]:
print(df.shape)
df = df.set_index("Attribute").T
print(df.shape)
df.index.name = "Planet"
print(df.shape)
df.reset_index(inplace=True)
print(df.shape)
df.columns.name = None
print(df.shape)

(20, 11)
(10, 20)
(10, 20)
(10, 21)
(10, 21)

In [4]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

a) Before transposing the shape was (20, 11) and after transposing it is (10, 21)

b) There were initially 20 rows and 11 columns. Now, there are 10 rows and 21 columns.

c) Of the four lines, the first uses the ["Attribute"] column as the new row index, essentially removing that column and just making it the actual titles, and then flipping the rows and columns. The second switches the index name from Attribute to Planet because the columns are now the already named attributes, while each row is a planet (indexing by planet). This is why the shape does not change between the first and second lines of code. Now that the index has been flipped and renamed, the third line of code is kind of the opposite of the first, making the planet index its own dedicated column (like what "Attribute" was before transposing). This adds a column, making the new shape (10, 21). The last line of code is a stylistic thing that technically removes column names (but I still have them when I print, which is good because otherwise they are arbitrary values and unknown meanings), so the shape stays the same.

d) The new shape isn't (11, 20) because after flipping, we don't want a row full of just strings of column names (apart from their actual names, which has to do with indexing and isn't part of the shape). We do want to differentiate by planet, which is the new row index anyway, hence the code that makes it the first column (which would come in handy for manipulations, plotting, etc). The main thing is that each row is filtered by planet and not by variable/ attribute, which again likely will be much easier for when we manipulate the data.

In [5]:
print(df.columns)

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

Of the columns, 16 have units, including: 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)','Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Obliquity to Orbit (deg)','Mean Temperature (C)', and 'Surface Pressure (bars)'.

5 do not have units: 'Planet', 'Orbital Eccentricity', 'Number of Moons', 'Ring System?', and 'Global Magnetic Field?'

please see above for part g, the whole transposed dataframe :)

### Honestly, I do want to do this assignment and will do it for my own knowledge either during dead week or after finals (depending on my workload), but right now I have more papers/ final projects due and as much as I enjoy this, I am aware I am a slow coder. So this is as far as I got for this one (and it took me way too long for how little progress it is, but thats a me issue and not an issue with the HW-- again I'm just slow). I doubt that this will cause me to not pass, and I know I don't want to ask for an extension since that cuts into your dead week time too.
# Thank you so much for a wonderful (and wonderfully informative) semester!